#*******************************************************************************
#* makefile.mk
#*------------------------------------------------------------------------------
#* Makefile used to generate the Application binaries (GNU ARM format).
#* This file was automatically generated by IngeDev. Please, do not edit!
#*******************************************************************************

#-------------------------------------------------------------------------------
# General constants
#-------------------------------------------------------------------------------
EMPTY :=
SPACE := $(EMPTY) $(EMPTY)

#-------------------------------------------------------------------------------
# Project and file names
#-------------------------------------------------------------------------------
# Project name
PROJECT_NAME    := Cless Custom PayPass 3.1
# Compiler version
COMPILER_VERSION:= GNU ARM 4.3.4 (HWT1/T2)
# Configuration name
CFG_NAME        := GNU_ARM_DEBUG_T2
# Target file name (without extension)
TRG_FILE_NAME   := CLESSCUSTOM
# Mapping file name
MAPPING_DEF_NAME:= mapping.def

#-------------------------------------------------------------------------------
# Directories
#-------------------------------------------------------------------------------
# Binaries directory
BIN_DIR         := Bin
# Object directory
OBJ_DIR         := Obj
# Build files directory
BUILD_FILES_DIR := BuildFiles

#-------------------------------------------------------------------------------
# Input files path for the current configuration
#-------------------------------------------------------------------------------
# Build files path
BUILD_FILES_PATH:= $(BUILD_FILES_DIR)/$(CFG_NAME)

#-------------------------------------------------------------------------------
# Output files path for the current configuration
#-------------------------------------------------------------------------------
# Object files path
OBJ_PATH        := $(OBJ_DIR)/$(CFG_NAME)
# Binary files path
BIN_PATH        := $(BIN_DIR)/$(CFG_NAME)

#-------------------------------------------------------------------------------
# Compiler, linker, assembler, ...
#-------------------------------------------------------------------------------
# Gnu Compiler executable
CC              := arm-elf-gcc.exe
# Gnu Assembler executable
AS              := arm-elf-as.exe
# Gnu Linker executable
LD              := arm-elf-ld.exe
# Gnu binary file transforming executable
OBJ_COPY        := arm-elf-objcopy.exe
# Gnu binary sections size executable
SIZE            := arm-elf-size.exe
# Gnu binary Obj Dump executable
OBJ_DUMP        := arm-elf-objdump.exe
#-------------------------------------------------------------------------------
# Gnu Win32 tools
#-------------------------------------------------------------------------------
# Remove tool
RM              := rm.exe -fr
# Make directory tool
MKDIR           := mkdir.exe -p
# Printf tool
PRINTF          := printf.exe

#-------------------------------------------------------------------------------
# Includes path used in compilation process
#-------------------------------------------------------------------------------
INCLUDES_PATH   := \
-IInc \
-IIncGen \
-IC:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/inc \
-IC:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/inc/ingenico \
-IC:/add-on\ Unattended\ 8.0.0.00/SDKTPLUS/HW_T2/gnu_434/inc \
-IC:/Easy\ Path\ to\ CLess\ 7.6.2.00/SDKTPLUS/HW_T2/gnu_434/inc \
-IC:/Easy\ Path\ to\ EMV\ 30.12.0.01/SDKTPLUS_Engine/HW_T2/gnu_434/inc \


#-------------------------------------------------------------------------------
# Libraries to be included during link operation
#-------------------------------------------------------------------------------
LIBS            := \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/BarCode_TPlus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/eft30tplus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/TRAP_TELIUM_PLUS.LIB \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/BCR_TPlus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/SECTPLUS.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/SEC_extend.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/Digest_TPlus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/dll_wifi_TPlus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/IP_TPlus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/LinkLayerExeInterface_TPlus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/SNMP_Tplus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/SSL_TPlus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/gps_dll.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/IPA280_TPlus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/ExtraGPRS.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/Mifare_TPlus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/TPass_TPlus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/GTL_TPlus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/NDEF.LIB \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/SNTP.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/XMLs_TPlus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/FMG_TPlus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/TlvTree_TPlus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/FTP_TPlus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/OSLAYER.LIB \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/LIBOS.LIB \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/libTmsCall_TPlus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/LIBGRAPHICS.LIB \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/GRAPHICLIB.LIB \
C:/add-on\ Unattended\ 8.0.0.00/SDKTPLUS/HW_T2/gnu_434/lib/AUDIT_TPlus.lib \
C:/add-on\ Unattended\ 8.0.0.00/SDKTPLUS/HW_T2/gnu_434/lib/DEXUCS_TPlus.lib \
C:/add-on\ Unattended\ 8.0.0.00/SDKTPLUS/HW_T2/gnu_434/lib/UCMC_TPlus.lib \
C:/add-on\ Unattended\ 8.0.0.00/SDKTPLUS/HW_T2/gnu_434/lib/UCMHOST_TPlus.lib \
C:/add-on\ Unattended\ 8.0.0.00/SDKTPLUS/HW_T2/gnu_434/lib/UCMSTART_TPlus.lib \
C:/add-on\ Unattended\ 8.0.0.00/SDKTPLUS/HW_T2/gnu_434/lib/UCI_TPlus.lib \
C:/add-on\ Unattended\ 8.0.0.00/SDKTPLUS/HW_T2/gnu_434/lib/DDCMP_TPlus.lib \
C:/add-on\ Unattended\ 8.0.0.00/SDKTPLUS/HW_T2/gnu_434/lib/GATEWAY_TPlus.lib \
C:/Easy\ Path\ to\ CLess\ 7.6.2.00/SDKTPLUS/HW_T2/gnu_434/lib/DEL_TPlus.lib \
C:/Easy\ Path\ to\ CLess\ 7.6.2.00/SDKTPLUS/HW_T2/gnu_434/lib/DiscoverDPASInterface_TPlus.lib \
C:/Easy\ Path\ to\ CLess\ 7.6.2.00/SDKTPLUS/HW_T2/gnu_434/lib/DiscoverInterface_TPlus.lib \
C:/Easy\ Path\ to\ CLess\ 7.6.2.00/SDKTPLUS/HW_T2/gnu_434/lib/eftposInterface_TPlus.lib \
C:/Easy\ Path\ to\ CLess\ 7.6.2.00/SDKTPLUS/HW_T2/gnu_434/lib/ExpressPayInterface_TPlus.lib \
C:/Easy\ Path\ to\ CLess\ 7.6.2.00/SDKTPLUS/HW_T2/gnu_434/lib/InteracInterface_TPlus.lib \
C:/Easy\ Path\ to\ CLess\ 7.6.2.00/SDKTPLUS/HW_T2/gnu_434/lib/JCBInterface_TPlus.lib \
C:/Easy\ Path\ to\ CLess\ 7.6.2.00/SDKTPLUS/HW_T2/gnu_434/lib/PayPassInterface_TPlus.lib \
C:/Easy\ Path\ to\ CLess\ 7.6.2.00/SDKTPLUS/HW_T2/gnu_434/lib/payWaveInterface_TPlus.lib \
C:/Easy\ Path\ to\ CLess\ 7.6.2.00/SDKTPLUS/HW_T2/gnu_434/lib/qPBOCInterface_TPlus.lib \
C:/Easy\ Path\ to\ CLess\ 7.6.2.00/SDKTPLUS/HW_T2/gnu_434/lib/QuickPassInterface_TPlus.lib \
C:/Easy\ Path\ to\ CLess\ 7.6.2.00/SDKTPLUS/HW_T2/gnu_434/lib/VisaWaveInterface_TPlus.lib \
C:/Easy\ Path\ to\ CLess\ 7.6.2.00/SDKTPLUS/HW_T2/gnu_434/lib/SDI_TPlus.lib \
C:/Easy\ Path\ to\ EMV\ 30.12.0.01/SDKTPLUS_Engine/HW_T2/gnu_434/lib/DEL_TPlus.lib \
C:/Easy\ Path\ to\ EMV\ 30.12.0.01/SDKTPLUS_Engine/HW_T2/gnu_434/lib/EmvDcInterface_TPlus.lib \
C:/Easy\ Path\ to\ EMV\ 30.12.0.01/SDKTPLUS_Engine/HW_T2/gnu_434/lib/EngineInterface_TPlus.lib \
C:/Easy\ Path\ to\ EMV\ 30.12.0.01/SDKTPLUS_Engine/HW_T2/gnu_434/lib/EmvCoChecksum_TPlus.lib \


#-------------------------------------------------------------------------------
# System libraries to be included during link operation
#-------------------------------------------------------------------------------
SYSTEM_LIBS     := \
-L D:/Ingenico/IngeDev_8.14.1.0/toolchains/gnuArm4/arm-elf/lib/thumb/soft/interwork -lsupc++ \
-L D:/Ingenico/IngeDev_8.14.1.0/toolchains/gnuArm4/arm-elf/lib/thumb/soft/interwork -lc \
-L D:/Ingenico/IngeDev_8.14.1.0/toolchains/gnuArm4/lib/gcc/arm-elf/4.3.4/thumb/soft/interwork -lgcc

#-------------------------------------------------------------------------------
# Compilation and link input files
#-------------------------------------------------------------------------------
# Mapping file location (used during link process)
MAP_DEF_LOCATION:= $(BUILD_FILES_PATH)/$(MAPPING_DEF_NAME)

#-------------------------------------------------------------------------------
# Result output files
#-------------------------------------------------------------------------------
# Binary file
BINARY_FILE     := $(BIN_PATH)/$(TRG_FILE_NAME).BIN

#-------------------------------------------------------------------------------
# Result Listing files
#-------------------------------------------------------------------------------
# Binary file
LST_FILE        := $(OBJ_PATH)/$(TRG_FILE_NAME).lst

#-------------------------------------------------------------------------------
# Intermediate files
#-------------------------------------------------------------------------------
# Result map file location
INTER_MAP_FILE        := $(OBJ_PATH)/$(TRG_FILE_NAME).map
# AXF file location
INTER_AXF_FILE        := $(OBJ_PATH)/$(TRG_FILE_NAME).axf
# ELF file location
INTER_ELF_FILE        := $(OBJ_PATH)/$(TRG_FILE_NAME).elf
# Start up file opt
STARTUP_BEGIN_FILE_OPT:= $(OBJ_PATH)/startupBeginfile.opt
STARTUP_END_FILE_OPT  := $(OBJ_PATH)/startupEndfile.opt
# Objects list files
OBJ_LIST_FILE         := $(OBJ_PATH)/obj_list_files.opt

#-------------------------------------------------------------------------------
# Default compiler, linker, assembler options
#-------------------------------------------------------------------------------
# Default compiler options
CC_DEF_OPTS     := -g -c -Wall -Wcast-align -mthumb-interwork -mlittle-endian -msoft-float -pipe -mcpu=arm920t -fomit-frame-pointer -fshort-enums -mstructure-size-boundary=8
# Default assembler options
AS_DEF_OPTS     := --gdwarf2 -mthumb-interwork -EL -mfpu=softfpa -march=armv4t -mcpu=arm9tdmi
# Default linker options
LD_DEF_OPTS     :=  -Map=$(INTER_MAP_FILE)
# Default linker options
OD_DEF_OPTS     := --disassemble --source --syms

#-------------------------------------------------------------------------------
# Specific compiler, linker, assembler options
#-------------------------------------------------------------------------------
# Specific compiler options
CC_SPEC_OPTS    := -mthumb -fno-exceptions -fstack-protector-all  -D_ING_GNU_ARM_DEBUG_T2
CC_SPEC_OPTS    +=  -D__FRAMEWORK_TELIUM_PLUS__=1 -D_EXPORT_=1 -D_PACKAGE_NAME_=TeliumPlusSDK -DSDK_VERSION=111600 -D__TELIUM2__=1
CC_SPEC_OPTS    +=  -D_EFT30_
CC_SPEC_OPTS    +=  -D_ING_APPLI_BINARY_NAME='"CLESSCUSTOM"' -D_SECDEL_ -D_USE_DEL_LIB_ -D_ING_APPLI_FAMILY='"CLESSCUSTOM"' -D_ING_APPLI_TYPE=0x122 -D_ING_APPLI_TELIUM1_FULL_BINARY_NAME='"CLESSCUSTOM.SGN"' -D_ING_APPLI_TELIUM2_FULL_BINARY_NAME='"CLESSCUSTOM.AGN"' -D_ING_APPLI_TELIUM_COMPATIBILITY='"Telium 2"' -D_ING_APPLI_SIGN_MODE='"Unsigned"' -D_ING_APPLI_DATA_FILE_BINARY_NAME='"${appli_data_file_binary_name}"' -D_ING_APPLI_FULL_DATA_FILE_BINARY_NAME='"DATA0122.PGN"' -D_ING_APPLI_DATA_FILE_TELIUM1_BINARY_NAME='"DATA0122.SGN"' -D_ING_APPLI_DATA_FILE_TELIUM2_BINARY_NAME='"DATA0122.PGN"' -D_ING_APPLI_CURRENT_CONFIG_NAME='"GNU_ARM_DEBUG_T2"' -D_ING_APPLI_FULL_BINARY_NAME='"CLESSCUSTOM.AGN"' $(INCLUDES_PATH)
# Specific assembler options
AS_SPEC_OPTS    := -mthumb  --defsym _ING_GNU_ARM_DEBUG_T2=1
AS_SPEC_OPTS    +=  $(INCLUDES_PATH)
# Specific linker options
LD_SPEC_OPTS    := 

#-------------------------------------------------------------------------------
# Compiler, linker, assembler options
# default + specific options
#-------------------------------------------------------------------------------
# Compiler options
CC_OPTS         := $(CC_DEF_OPTS) $(CC_SPEC_OPTS)
# Assembler options
AS_OPTS         := $(AS_DEF_OPTS) $(AS_SPEC_OPTS)
# Linker options
LD_OPTS         := $(LD_DEF_OPTS) $(LD_SPEC_OPTS)
#ObjDump options
OD_OPTS         := $(OD_DEF_OPTS)

#-------------------------------------------------------------------------------
# SRC_OBJS is the list of the project object files
#-------------------------------------------------------------------------------
SRC_OBJS        := \
$(OBJ_PATH)/ClessSample_Batch.o \
$(OBJ_PATH)/ClessSample_BlackList.o \
$(OBJ_PATH)/ClessSample_Comevent.o \
$(OBJ_PATH)/ClessSample_Common.o \
$(OBJ_PATH)/ClessSample_Customisation.o \
$(OBJ_PATH)/ClessSample_DataExchange.o \
$(OBJ_PATH)/ClessSample_Discover.o \
$(OBJ_PATH)/ClessSample_Disk.o \
$(OBJ_PATH)/ClessSample_DumpData.o \
$(OBJ_PATH)/ClessSample_ExplicitSelection.o \
$(OBJ_PATH)/ClessSample_ExpressPay.o \
$(OBJ_PATH)/ClessSample_Fill.o \
$(OBJ_PATH)/ClessSample_FinancialCommunication.o \
$(OBJ_PATH)/ClessSample_GlobalTransactionData.o \
$(OBJ_PATH)/ClessSample_Goal.o \
$(OBJ_PATH)/ClessSample_GuiState.o \
$(OBJ_PATH)/ClessSample_Interac.o \
$(OBJ_PATH)/ClessSample_lang.o \
$(OBJ_PATH)/ClessSample_Menu.o \
$(OBJ_PATH)/ClessSample_NameList.o \
$(OBJ_PATH)/ClessSample_Parameters.o \
$(OBJ_PATH)/ClessSample_PayPass.o \
$(OBJ_PATH)/ClessSample_payWave.o \
$(OBJ_PATH)/ClessSample_PinEnManagement.o \
$(OBJ_PATH)/ClessSample_PinEntryGoal.o \
$(OBJ_PATH)/ClessSample_PinManagement.o \
$(OBJ_PATH)/ClessSample_Receipt.o \
$(OBJ_PATH)/ClessSample_Scan.o \
$(OBJ_PATH)/ClessSample_Settings.o \
$(OBJ_PATH)/ClessSample_Term.o \
$(OBJ_PATH)/ClessSample_TestPlan.o \
$(OBJ_PATH)/ClessSample_Torn.o \
$(OBJ_PATH)/ClessSample_TransactionFile.o \
$(OBJ_PATH)/ClessSample_Unattended.o \
$(OBJ_PATH)/ClessSample_VisaWave.o \
$(OBJ_PATH)/ClessSample_XML.o \
$(OBJ_PATH)/Entry.o \
$(OBJ_PATH)/perf_log.o \
$(OBJ_PATH)/servcomm.o \
$(OBJ_PATH)/UserInterfaceHelpers.o \
$(OBJ_PATH)/ComEthernet.o \
$(OBJ_PATH)/ComGPRS.o \
$(OBJ_PATH)/ComSerial.o \
$(OBJ_PATH)/ComUSB.o \
$(OBJ_PATH)/convert.o \
$(OBJ_PATH)/cu_base.o \
$(OBJ_PATH)/cu_batch.o \
$(OBJ_PATH)/cu_black.o \
$(OBJ_PATH)/cu_comm.o \
$(OBJ_PATH)/cu_disk.o \
$(OBJ_PATH)/cu_entry.o \
$(OBJ_PATH)/cu_file.o \
$(OBJ_PATH)/cu_lang.o \
$(OBJ_PATH)/cu_logos.o \
$(OBJ_PATH)/cu_mess_naps.o \
$(OBJ_PATH)/cu_mess.o \
$(OBJ_PATH)/cu_more_Naps.o \
$(OBJ_PATH)/cu_more.o \
$(OBJ_PATH)/cu_param.o \
$(OBJ_PATH)/cu_pin.o \
$(OBJ_PATH)/cu_pinen.o \
$(OBJ_PATH)/cu_receipt.o \
$(OBJ_PATH)/cu_serv.o \
$(OBJ_PATH)/cu_servcomm.o \
$(OBJ_PATH)/cu_str.o \
$(OBJ_PATH)/cu_term.o \
$(OBJ_PATH)/cu_trfile.o \
$(OBJ_PATH)/cu_UserInterface.o \
$(OBJ_PATH)/cu_UserInterfaceDisplay.o \
$(OBJ_PATH)/cu_UserInterfaceHelpers.o \
$(OBJ_PATH)/EPSTOOL_Convert.o \
$(OBJ_PATH)/EPSTOOL_PinEntry.o \
$(OBJ_PATH)/EPSTOOL_TlvTree.o \
$(OBJ_PATH)/EPSTOOL_Unicode.o \
$(OBJ_PATH)/gestion_param.o \
$(OBJ_PATH)/Globals.o \
$(OBJ_PATH)/Gpinpad.o \
$(OBJ_PATH)/Magnetic.o \
$(OBJ_PATH)/Mapapp.o \
$(OBJ_PATH)/MyTlvTree.o \
$(OBJ_PATH)/Naps8583.o \
$(OBJ_PATH)/NapsAllFile.o \
$(OBJ_PATH)/NapsCard.o \
$(OBJ_PATH)/Napsdes_m.o \
$(OBJ_PATH)/NapsEdition.o \
$(OBJ_PATH)/NapsEmvDat.o \
$(OBJ_PATH)/NapsLop.o \
$(OBJ_PATH)/NapsTools.o \
$(OBJ_PATH)/NapsTra.o \
$(OBJ_PATH)/Timer.o \
$(OBJ_PATH)/TlvTreeDel.o \
$(OBJ_PATH)/TrackIac.o \
$(OBJ_PATH)/Utility.o \
$(OBJ_PATH)/Naps_ClessSample_Receipt.o \
$(OBJ_PATH)/NapsAuto.o \
$(OBJ_PATH)/APCLESS_Explicit.o \
$(OBJ_PATH)/APCLESS_GuiGoal.o \
$(OBJ_PATH)/APCLESS_Kernel.o \
$(OBJ_PATH)/APCLESS_ParamTrn.o \
$(OBJ_PATH)/APCLESS_PayPass.o \
$(OBJ_PATH)/APCLESS_PayPassTorn.o \
$(OBJ_PATH)/APCLESS_payWave.o \
$(OBJ_PATH)/APCLESS_Selection.o \
$(OBJ_PATH)/APCLESS_Services.o \
$(OBJ_PATH)/APCLESS_ServicesImplicit.o \
$(OBJ_PATH)/APCLESS_ServicesKernel.o \
$(OBJ_PATH)/APCLESS_ServicesManager.o \
$(OBJ_PATH)/APCLESS_Tools.o \

#-------------------------------------------------------------------------------
# Dependencies
#-------------------------------------------------------------------------------
DEPENDENCIES    := \
$(BUILD_FILES_PATH)/makefile.mk

#===============================================================================
# Rule to make the project
#===============================================================================
#-------------------------------------------------------------------------------
# Rule for the binary files generation
#-------------------------------------------------------------------------------
$(BINARY_FILE): $(INTER_ELF_FILE)
	$(OBJ_COPY) -O binary $(INTER_AXF_FILE) $@
	@echo "'$@' binary file generated."

#===============================================================================
# Rule for startup files rules generation
#===============================================================================
START_OBJS := C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/startfiles/cstartupTplus.o \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/startfiles/libcpatch.o \

END_OBJS   := 

#===============================================================================
# Rule for the link process
#===============================================================================
#-------------------------------------------------------------------------------
# Rule for the axf file generation
#-------------------------------------------------------------------------------
$(INTER_AXF_FILE): $(MAP_DEF_LOCATION) $(SRC_OBJS) $(LIBS)
	@echo "'$@' link in progress..."
	$(LD) $(LD_OPTS) \
	-T $< \
	-o $@ \
	$(START_OBJS)\
	$(SRC_OBJS) \
	 --start-group \
	$(LIBS) $(SYSTEM_LIBS) \
	--end-group \
	$(END_OBJS)\


#-------------------------------------------------------------------------------
# Rule for the elf file generation
#-------------------------------------------------------------------------------
$(INTER_ELF_FILE): $(INTER_AXF_FILE)
	$(SIZE) -A $< > $@

#===============================================================================
# Rule for the .lst Generation
#===============================================================================
$(LST_FILE): $(INTER_AXF_FILE)
	$(OBJ_DUMP) $(OD_OPTS) $<  > $@
	@echo "'$@' lst file generated."

#===============================================================================
# Rule for the compilation process
#===============================================================================
ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_Batch.d
endif
$(OBJ_PATH)/ClessSample_Batch.o: Src/ClessSample_Batch.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_Batch.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_Batch.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_BlackList.d
endif
$(OBJ_PATH)/ClessSample_BlackList.o: Src/ClessSample_BlackList.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_BlackList.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_BlackList.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_Comevent.d
endif
$(OBJ_PATH)/ClessSample_Comevent.o: Src/ClessSample_Comevent.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_Comevent.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_Comevent.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_Common.d
endif
$(OBJ_PATH)/ClessSample_Common.o: Src/ClessSample_Common.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_Common.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_Common.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_Customisation.d
endif
$(OBJ_PATH)/ClessSample_Customisation.o: Src/ClessSample_Customisation.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_Customisation.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_Customisation.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_DataExchange.d
endif
$(OBJ_PATH)/ClessSample_DataExchange.o: Src/ClessSample_DataExchange.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_DataExchange.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_DataExchange.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_Discover.d
endif
$(OBJ_PATH)/ClessSample_Discover.o: Src/ClessSample_Discover.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_Discover.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_Discover.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_Disk.d
endif
$(OBJ_PATH)/ClessSample_Disk.o: Src/ClessSample_Disk.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_Disk.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_Disk.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_DumpData.d
endif
$(OBJ_PATH)/ClessSample_DumpData.o: Src/ClessSample_DumpData.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_DumpData.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_DumpData.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_ExplicitSelection.d
endif
$(OBJ_PATH)/ClessSample_ExplicitSelection.o: Src/ClessSample_ExplicitSelection.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_ExplicitSelection.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_ExplicitSelection.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_ExpressPay.d
endif
$(OBJ_PATH)/ClessSample_ExpressPay.o: Src/ClessSample_ExpressPay.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_ExpressPay.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_ExpressPay.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_Fill.d
endif
$(OBJ_PATH)/ClessSample_Fill.o: Src/ClessSample_Fill.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_Fill.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_Fill.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_FinancialCommunication.d
endif
$(OBJ_PATH)/ClessSample_FinancialCommunication.o: Src/ClessSample_FinancialCommunication.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_FinancialCommunication.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_FinancialCommunication.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_GlobalTransactionData.d
endif
$(OBJ_PATH)/ClessSample_GlobalTransactionData.o: Src/ClessSample_GlobalTransactionData.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_GlobalTransactionData.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_GlobalTransactionData.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_Goal.d
endif
$(OBJ_PATH)/ClessSample_Goal.o: Src/ClessSample_Goal.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_Goal.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_Goal.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_GuiState.d
endif
$(OBJ_PATH)/ClessSample_GuiState.o: Src/ClessSample_GuiState.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_GuiState.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_GuiState.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_Interac.d
endif
$(OBJ_PATH)/ClessSample_Interac.o: Src/ClessSample_Interac.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_Interac.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_Interac.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_lang.d
endif
$(OBJ_PATH)/ClessSample_lang.o: Src/ClessSample_lang.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_lang.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_lang.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_Menu.d
endif
$(OBJ_PATH)/ClessSample_Menu.o: Src/ClessSample_Menu.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_Menu.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_Menu.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_NameList.d
endif
$(OBJ_PATH)/ClessSample_NameList.o: Src/ClessSample_NameList.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_NameList.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_NameList.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_Parameters.d
endif
$(OBJ_PATH)/ClessSample_Parameters.o: Src/ClessSample_Parameters.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_Parameters.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_Parameters.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_PayPass.d
endif
$(OBJ_PATH)/ClessSample_PayPass.o: Src/ClessSample_PayPass.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_PayPass.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_PayPass.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_payWave.d
endif
$(OBJ_PATH)/ClessSample_payWave.o: Src/ClessSample_payWave.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_payWave.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_payWave.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_PinEnManagement.d
endif
$(OBJ_PATH)/ClessSample_PinEnManagement.o: Src/ClessSample_PinEnManagement.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_PinEnManagement.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_PinEnManagement.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_PinEntryGoal.d
endif
$(OBJ_PATH)/ClessSample_PinEntryGoal.o: Src/ClessSample_PinEntryGoal.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_PinEntryGoal.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_PinEntryGoal.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_PinManagement.d
endif
$(OBJ_PATH)/ClessSample_PinManagement.o: Src/ClessSample_PinManagement.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_PinManagement.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_PinManagement.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_Receipt.d
endif
$(OBJ_PATH)/ClessSample_Receipt.o: Src/ClessSample_Receipt.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_Receipt.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_Receipt.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_Scan.d
endif
$(OBJ_PATH)/ClessSample_Scan.o: Src/ClessSample_Scan.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_Scan.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_Scan.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_Settings.d
endif
$(OBJ_PATH)/ClessSample_Settings.o: Src/ClessSample_Settings.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_Settings.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_Settings.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_Term.d
endif
$(OBJ_PATH)/ClessSample_Term.o: Src/ClessSample_Term.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_Term.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_Term.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_TestPlan.d
endif
$(OBJ_PATH)/ClessSample_TestPlan.o: Src/ClessSample_TestPlan.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_TestPlan.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_TestPlan.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_Torn.d
endif
$(OBJ_PATH)/ClessSample_Torn.o: Src/ClessSample_Torn.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_Torn.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_Torn.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_TransactionFile.d
endif
$(OBJ_PATH)/ClessSample_TransactionFile.o: Src/ClessSample_TransactionFile.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_TransactionFile.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_TransactionFile.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_Unattended.d
endif
$(OBJ_PATH)/ClessSample_Unattended.o: Src/ClessSample_Unattended.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_Unattended.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_Unattended.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_VisaWave.d
endif
$(OBJ_PATH)/ClessSample_VisaWave.o: Src/ClessSample_VisaWave.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_VisaWave.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_VisaWave.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ClessSample_XML.d
endif
$(OBJ_PATH)/ClessSample_XML.o: Src/ClessSample_XML.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ClessSample_XML.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ClessSample_XML.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Entry.d
endif
$(OBJ_PATH)/Entry.o: Src/Entry.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/Entry.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Entry.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/perf_log.d
endif
$(OBJ_PATH)/perf_log.o: Src/perf_log.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/perf_log.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/perf_log.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/servcomm.d
endif
$(OBJ_PATH)/servcomm.o: Src/servcomm.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/servcomm.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/servcomm.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/UserInterfaceHelpers.d
endif
$(OBJ_PATH)/UserInterfaceHelpers.o: Src/UserInterfaceHelpers.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/UserInterfaceHelpers.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/UserInterfaceHelpers.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ComEthernet.d
endif
$(OBJ_PATH)/ComEthernet.o: Src/ComEthernet.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ComEthernet.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ComEthernet.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ComGPRS.d
endif
$(OBJ_PATH)/ComGPRS.o: Src/ComGPRS.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ComGPRS.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ComGPRS.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ComSerial.d
endif
$(OBJ_PATH)/ComSerial.o: Src/ComSerial.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ComSerial.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ComSerial.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ComUSB.d
endif
$(OBJ_PATH)/ComUSB.o: Src/ComUSB.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/ComUSB.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ComUSB.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/convert.d
endif
$(OBJ_PATH)/convert.o: Src/convert.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/convert.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/convert.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_base.d
endif
$(OBJ_PATH)/cu_base.o: Src/cu_base.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_base.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_base.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_batch.d
endif
$(OBJ_PATH)/cu_batch.o: Src/cu_batch.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_batch.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_batch.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_black.d
endif
$(OBJ_PATH)/cu_black.o: Src/cu_black.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_black.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_black.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_comm.d
endif
$(OBJ_PATH)/cu_comm.o: Src/cu_comm.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_comm.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_comm.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_disk.d
endif
$(OBJ_PATH)/cu_disk.o: Src/cu_disk.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_disk.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_disk.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_entry.d
endif
$(OBJ_PATH)/cu_entry.o: Src/cu_entry.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_entry.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_entry.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_file.d
endif
$(OBJ_PATH)/cu_file.o: Src/cu_file.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_file.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_file.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_lang.d
endif
$(OBJ_PATH)/cu_lang.o: Src/cu_lang.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_lang.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_lang.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_logos.d
endif
$(OBJ_PATH)/cu_logos.o: Src/cu_logos.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_logos.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_logos.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_mess_naps.d
endif
$(OBJ_PATH)/cu_mess_naps.o: Src/cu_mess_naps.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_mess_naps.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_mess_naps.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_mess.d
endif
$(OBJ_PATH)/cu_mess.o: Src/cu_mess.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_mess.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_mess.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_more_Naps.d
endif
$(OBJ_PATH)/cu_more_Naps.o: Src/cu_more_Naps.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_more_Naps.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_more_Naps.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_more.d
endif
$(OBJ_PATH)/cu_more.o: Src/cu_more.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_more.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_more.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_param.d
endif
$(OBJ_PATH)/cu_param.o: Src/cu_param.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_param.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_param.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_pin.d
endif
$(OBJ_PATH)/cu_pin.o: Src/cu_pin.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_pin.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_pin.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_pinen.d
endif
$(OBJ_PATH)/cu_pinen.o: Src/cu_pinen.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_pinen.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_pinen.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_receipt.d
endif
$(OBJ_PATH)/cu_receipt.o: Src/cu_receipt.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_receipt.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_receipt.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_serv.d
endif
$(OBJ_PATH)/cu_serv.o: Src/cu_serv.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_serv.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_serv.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_servcomm.d
endif
$(OBJ_PATH)/cu_servcomm.o: Src/cu_servcomm.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_servcomm.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_servcomm.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_str.d
endif
$(OBJ_PATH)/cu_str.o: Src/cu_str.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_str.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_str.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_term.d
endif
$(OBJ_PATH)/cu_term.o: Src/cu_term.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_term.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_term.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_trfile.d
endif
$(OBJ_PATH)/cu_trfile.o: Src/cu_trfile.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_trfile.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_trfile.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_UserInterface.d
endif
$(OBJ_PATH)/cu_UserInterface.o: Src/cu_UserInterface.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_UserInterface.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_UserInterface.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_UserInterfaceDisplay.d
endif
$(OBJ_PATH)/cu_UserInterfaceDisplay.o: Src/cu_UserInterfaceDisplay.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_UserInterfaceDisplay.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_UserInterfaceDisplay.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_UserInterfaceHelpers.d
endif
$(OBJ_PATH)/cu_UserInterfaceHelpers.o: Src/cu_UserInterfaceHelpers.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_UserInterfaceHelpers.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_UserInterfaceHelpers.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/EPSTOOL_Convert.d
endif
$(OBJ_PATH)/EPSTOOL_Convert.o: Src/EPSTOOL_Convert.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/EPSTOOL_Convert.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/EPSTOOL_Convert.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/EPSTOOL_PinEntry.d
endif
$(OBJ_PATH)/EPSTOOL_PinEntry.o: Src/EPSTOOL_PinEntry.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/EPSTOOL_PinEntry.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/EPSTOOL_PinEntry.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/EPSTOOL_TlvTree.d
endif
$(OBJ_PATH)/EPSTOOL_TlvTree.o: Src/EPSTOOL_TlvTree.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/EPSTOOL_TlvTree.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/EPSTOOL_TlvTree.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/EPSTOOL_Unicode.d
endif
$(OBJ_PATH)/EPSTOOL_Unicode.o: Src/EPSTOOL_Unicode.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/EPSTOOL_Unicode.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/EPSTOOL_Unicode.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/gestion_param.d
endif
$(OBJ_PATH)/gestion_param.o: Src/gestion_param.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/gestion_param.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/gestion_param.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Globals.d
endif
$(OBJ_PATH)/Globals.o: Src/Globals.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/Globals.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Globals.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Gpinpad.d
endif
$(OBJ_PATH)/Gpinpad.o: Src/Gpinpad.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/Gpinpad.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Gpinpad.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Magnetic.d
endif
$(OBJ_PATH)/Magnetic.o: Src/Magnetic.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/Magnetic.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Magnetic.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Mapapp.d
endif
$(OBJ_PATH)/Mapapp.o: Src/Mapapp.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/Mapapp.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Mapapp.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/MyTlvTree.d
endif
$(OBJ_PATH)/MyTlvTree.o: Src/MyTlvTree.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/MyTlvTree.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/MyTlvTree.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Naps8583.d
endif
$(OBJ_PATH)/Naps8583.o: Src/Naps8583.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/Naps8583.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Naps8583.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/NapsAllFile.d
endif
$(OBJ_PATH)/NapsAllFile.o: Src/NapsAllFile.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/NapsAllFile.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/NapsAllFile.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/NapsCard.d
endif
$(OBJ_PATH)/NapsCard.o: Src/NapsCard.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/NapsCard.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/NapsCard.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Napsdes_m.d
endif
$(OBJ_PATH)/Napsdes_m.o: Src/Napsdes_m.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/Napsdes_m.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Napsdes_m.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/NapsEdition.d
endif
$(OBJ_PATH)/NapsEdition.o: Src/NapsEdition.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/NapsEdition.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/NapsEdition.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/NapsEmvDat.d
endif
$(OBJ_PATH)/NapsEmvDat.o: Src/NapsEmvDat.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/NapsEmvDat.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/NapsEmvDat.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/NapsLop.d
endif
$(OBJ_PATH)/NapsLop.o: Src/NapsLop.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/NapsLop.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/NapsLop.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/NapsTools.d
endif
$(OBJ_PATH)/NapsTools.o: Src/NapsTools.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/NapsTools.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/NapsTools.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/NapsTra.d
endif
$(OBJ_PATH)/NapsTra.o: Src/NapsTra.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/NapsTra.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/NapsTra.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Timer.d
endif
$(OBJ_PATH)/Timer.o: Src/Timer.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/Timer.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Timer.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/TlvTreeDel.d
endif
$(OBJ_PATH)/TlvTreeDel.o: Src/TlvTreeDel.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/TlvTreeDel.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/TlvTreeDel.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/TrackIac.d
endif
$(OBJ_PATH)/TrackIac.o: Src/TrackIac.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/TrackIac.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/TrackIac.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Utility.d
endif
$(OBJ_PATH)/Utility.o: Src/Utility.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/Utility.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Utility.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Naps_ClessSample_Receipt.d
endif
$(OBJ_PATH)/Naps_ClessSample_Receipt.o: Src/Naps_ClessSample_Receipt.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/Naps_ClessSample_Receipt.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Naps_ClessSample_Receipt.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/NapsAuto.d
endif
$(OBJ_PATH)/NapsAuto.o: Src/NapsAuto.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/NapsAuto.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/NapsAuto.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/APCLESS_Explicit.d
endif
$(OBJ_PATH)/APCLESS_Explicit.o: Src/APCLESS_Explicit.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/APCLESS_Explicit.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/APCLESS_Explicit.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/APCLESS_GuiGoal.d
endif
$(OBJ_PATH)/APCLESS_GuiGoal.o: Src/APCLESS_GuiGoal.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/APCLESS_GuiGoal.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/APCLESS_GuiGoal.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/APCLESS_Kernel.d
endif
$(OBJ_PATH)/APCLESS_Kernel.o: Src/APCLESS_Kernel.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/APCLESS_Kernel.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/APCLESS_Kernel.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/APCLESS_ParamTrn.d
endif
$(OBJ_PATH)/APCLESS_ParamTrn.o: Src/APCLESS_ParamTrn.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/APCLESS_ParamTrn.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/APCLESS_ParamTrn.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/APCLESS_PayPass.d
endif
$(OBJ_PATH)/APCLESS_PayPass.o: Src/APCLESS_PayPass.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/APCLESS_PayPass.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/APCLESS_PayPass.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/APCLESS_PayPassTorn.d
endif
$(OBJ_PATH)/APCLESS_PayPassTorn.o: Src/APCLESS_PayPassTorn.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/APCLESS_PayPassTorn.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/APCLESS_PayPassTorn.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/APCLESS_payWave.d
endif
$(OBJ_PATH)/APCLESS_payWave.o: Src/APCLESS_payWave.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/APCLESS_payWave.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/APCLESS_payWave.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/APCLESS_Selection.d
endif
$(OBJ_PATH)/APCLESS_Selection.o: Src/APCLESS_Selection.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/APCLESS_Selection.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/APCLESS_Selection.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/APCLESS_Services.d
endif
$(OBJ_PATH)/APCLESS_Services.o: Src/APCLESS_Services.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/APCLESS_Services.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/APCLESS_Services.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/APCLESS_ServicesImplicit.d
endif
$(OBJ_PATH)/APCLESS_ServicesImplicit.o: Src/APCLESS_ServicesImplicit.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/APCLESS_ServicesImplicit.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/APCLESS_ServicesImplicit.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/APCLESS_ServicesKernel.d
endif
$(OBJ_PATH)/APCLESS_ServicesKernel.o: Src/APCLESS_ServicesKernel.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/APCLESS_ServicesKernel.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/APCLESS_ServicesKernel.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/APCLESS_ServicesManager.d
endif
$(OBJ_PATH)/APCLESS_ServicesManager.o: Src/APCLESS_ServicesManager.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/APCLESS_ServicesManager.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/APCLESS_ServicesManager.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/APCLESS_Tools.d
endif
$(OBJ_PATH)/APCLESS_Tools.o: Src/APCLESS_Tools.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/APCLESS_Tools.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/APCLESS_Tools.o)
	@echo "done!"
endif


#===============================================================================
# Rule for project name and configuration name display
#===============================================================================
.PHONY: displayInfo
displayInfo:
	@echo "                                     *-*-*"
	@echo "--- Project '$(PROJECT_NAME)', Configuration '$(CFG_NAME)', Compiler '$(COMPILER_VERSION)' ---"

#===============================================================================
# Rule for build target progress info display
#===============================================================================
.PHONY: displayBuildInProgress
displayBuildInProgress:
	@echo "Build in progress..."

#===============================================================================
# Rule for output directories creation
#===============================================================================
createObjDir: | $(OBJ_PATH)

$(OBJ_PATH):
	@$(MKDIR) "$(OBJ_PATH)"

createBinDir: | $(BIN_PATH)

$(BIN_PATH):
	@$(MKDIR) "$(BIN_PATH)"


#===============================================================================
# Make build rule
#===============================================================================
.PHONY: build
build: displayInfo displayBuildInProgress createObjDir createBinDir $(BINARY_FILE)
	@echo "done!"
