#*******************************************************************************
#* makefile.mk
#*------------------------------------------------------------------------------
#* Makefile used to generate the Application binaries (GNU ARM format).
#* This file was automatically generated by IngeDev. Please, do not edit!
#*******************************************************************************

#-------------------------------------------------------------------------------
# General constants
#-------------------------------------------------------------------------------
EMPTY :=
SPACE := $(EMPTY) $(EMPTY)

#-------------------------------------------------------------------------------
# Project and file names
#-------------------------------------------------------------------------------
# Project name
PROJECT_NAME    := emv_custom
# Compiler version
COMPILER_VERSION:= GNU ARM 4.3.4 (HWT1/T2)
# Configuration name
CFG_NAME        := GNU_ARM_DEBUG_T2
# Target file name (without extension)
TRG_FILE_NAME   := EMV_CUSTOM
# Mapping file name
MAPPING_DEF_NAME:= mapping.def

#-------------------------------------------------------------------------------
# Directories
#-------------------------------------------------------------------------------
# Binaries directory
BIN_DIR         := Bin
# Object directory
OBJ_DIR         := Obj
# Build files directory
BUILD_FILES_DIR := BuildFiles

#-------------------------------------------------------------------------------
# Input files path for the current configuration
#-------------------------------------------------------------------------------
# Build files path
BUILD_FILES_PATH:= $(BUILD_FILES_DIR)/$(CFG_NAME)

#-------------------------------------------------------------------------------
# Output files path for the current configuration
#-------------------------------------------------------------------------------
# Object files path
OBJ_PATH        := $(OBJ_DIR)/$(CFG_NAME)
# Binary files path
BIN_PATH        := $(BIN_DIR)/$(CFG_NAME)

#-------------------------------------------------------------------------------
# Compiler, linker, assembler, ...
#-------------------------------------------------------------------------------
# Gnu Compiler executable
CC              := arm-elf-gcc.exe
# Gnu Assembler executable
AS              := arm-elf-as.exe
# Gnu Linker executable
LD              := arm-elf-ld.exe
# Gnu binary file transforming executable
OBJ_COPY        := arm-elf-objcopy.exe
# Gnu binary sections size executable
SIZE            := arm-elf-size.exe
# Gnu binary Obj Dump executable
OBJ_DUMP        := arm-elf-objdump.exe
#-------------------------------------------------------------------------------
# Gnu Win32 tools
#-------------------------------------------------------------------------------
# Remove tool
RM              := rm.exe -fr
# Make directory tool
MKDIR           := mkdir.exe -p
# Printf tool
PRINTF          := printf.exe

#-------------------------------------------------------------------------------
# Includes path used in compilation process
#-------------------------------------------------------------------------------
INCLUDES_PATH   := \
-IInc \
-IIncGen \
-IC:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/inc \
-IC:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/inc/ingenico \
-IC:/Easy\ Path\ to\ EMV\ 30.12.0.01/SDKTPLUS_Engine/HW_T2/gnu_434/inc \


#-------------------------------------------------------------------------------
# Libraries to be included during link operation
#-------------------------------------------------------------------------------
LIBS            := \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/BarCode_TPlus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/eft30tplus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/TRAP_TELIUM_PLUS.LIB \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/BCR_TPlus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/SECTPLUS.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/SEC_extend.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/Digest_TPlus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/dll_wifi_TPlus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/IP_TPlus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/LinkLayerExeInterface_TPlus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/SNMP_Tplus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/SSL_TPlus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/gps_dll.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/IPA280_TPlus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/ExtraGPRS.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/Mifare_TPlus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/TPass_TPlus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/GTL_TPlus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/NDEF.LIB \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/SNTP.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/XMLs_TPlus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/FMG_TPlus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/TlvTree_TPlus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/FTP_TPlus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/OSLAYER.LIB \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/LIBOS.LIB \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/libTmsCall_TPlus.lib \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/LIBGRAPHICS.LIB \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/lib/GRAPHICLIB.LIB \
C:/Easy\ Path\ to\ EMV\ 30.12.0.01/SDKTPLUS_Engine/HW_T2/gnu_434/lib/DEL_TPlus.lib \
C:/Easy\ Path\ to\ EMV\ 30.12.0.01/SDKTPLUS_Engine/HW_T2/gnu_434/lib/EmvDcInterface_TPlus.lib \
C:/Easy\ Path\ to\ EMV\ 30.12.0.01/SDKTPLUS_Engine/HW_T2/gnu_434/lib/EngineInterface_TPlus.lib \
C:/Easy\ Path\ to\ EMV\ 30.12.0.01/SDKTPLUS_Engine/HW_T2/gnu_434/lib/EmvCoChecksum_TPlus.lib \


#-------------------------------------------------------------------------------
# System libraries to be included during link operation
#-------------------------------------------------------------------------------
SYSTEM_LIBS     := \
-L D:/Ingenico/IngeDev_8.14.1.0/toolchains/gnuArm4/arm-elf/lib/thumb/soft/interwork -lsupc++ \
-L D:/Ingenico/IngeDev_8.14.1.0/toolchains/gnuArm4/arm-elf/lib/thumb/soft/interwork -lc \
-L D:/Ingenico/IngeDev_8.14.1.0/toolchains/gnuArm4/lib/gcc/arm-elf/4.3.4/thumb/soft/interwork -lgcc

#-------------------------------------------------------------------------------
# Compilation and link input files
#-------------------------------------------------------------------------------
# Mapping file location (used during link process)
MAP_DEF_LOCATION:= $(BUILD_FILES_PATH)/$(MAPPING_DEF_NAME)

#-------------------------------------------------------------------------------
# Result output files
#-------------------------------------------------------------------------------
# Binary file
BINARY_FILE     := $(BIN_PATH)/$(TRG_FILE_NAME).BIN

#-------------------------------------------------------------------------------
# Result Listing files
#-------------------------------------------------------------------------------
# Binary file
LST_FILE        := $(OBJ_PATH)/$(TRG_FILE_NAME).lst

#-------------------------------------------------------------------------------
# Intermediate files
#-------------------------------------------------------------------------------
# Result map file location
INTER_MAP_FILE        := $(OBJ_PATH)/$(TRG_FILE_NAME).map
# AXF file location
INTER_AXF_FILE        := $(OBJ_PATH)/$(TRG_FILE_NAME).axf
# ELF file location
INTER_ELF_FILE        := $(OBJ_PATH)/$(TRG_FILE_NAME).elf
# Start up file opt
STARTUP_BEGIN_FILE_OPT:= $(OBJ_PATH)/startupBeginfile.opt
STARTUP_END_FILE_OPT  := $(OBJ_PATH)/startupEndfile.opt
# Objects list files
OBJ_LIST_FILE         := $(OBJ_PATH)/obj_list_files.opt

#-------------------------------------------------------------------------------
# Default compiler, linker, assembler options
#-------------------------------------------------------------------------------
# Default compiler options
CC_DEF_OPTS     := -g -c -Wall -Wcast-align -mthumb-interwork -mlittle-endian -msoft-float -pipe -mcpu=arm920t -fomit-frame-pointer -fshort-enums -mstructure-size-boundary=8
# Default assembler options
AS_DEF_OPTS     := --gdwarf2 -mthumb-interwork -EL -mfpu=softfpa -march=armv4t -mcpu=arm9tdmi
# Default linker options
LD_DEF_OPTS     :=  -Map=$(INTER_MAP_FILE)
# Default linker options
OD_DEF_OPTS     := --disassemble --source --syms

#-------------------------------------------------------------------------------
# Specific compiler, linker, assembler options
#-------------------------------------------------------------------------------
# Specific compiler options
CC_SPEC_OPTS    := -mthumb -fno-exceptions -fstack-protector-all  -D_ING_GNU_ARM_DEBUG_T2
CC_SPEC_OPTS    +=  -D__FRAMEWORK_TELIUM_PLUS__=1 -D_EXPORT_=1 -D_PACKAGE_NAME_=TeliumPlusSDK -DSDK_VERSION=111600 -D__TELIUM2__=1
CC_SPEC_OPTS    +=  -D_ING_APPLI_BINARY_NAME='"EMV_CUSTOM"' -D_ING_APPLI_FAMILY='"emv_custom"' -D_ING_APPLI_TYPE=0x57a9 -D_ING_APPLI_TELIUM1_FULL_BINARY_NAME='"EMV_CUSTOM.SGN"' -D_ING_APPLI_TELIUM2_FULL_BINARY_NAME='"EMV_CUSTOM.AGN"' -D_ING_APPLI_TELIUM_COMPATIBILITY='"Telium 2"' -D_ING_APPLI_SIGN_MODE='"Unsigned"' -D_ING_APPLI_DATA_FILE_BINARY_NAME='"DATA57A9"' -D_ING_APPLI_FULL_DATA_FILE_BINARY_NAME='"DATA57A9.PGN"' -D_ING_APPLI_DATA_FILE_TELIUM1_BINARY_NAME='"DATA57A9.SGN"' -D_ING_APPLI_DATA_FILE_TELIUM2_BINARY_NAME='"DATA57A9.PGN"' -D_ING_APPLI_CURRENT_CONFIG_NAME='"GNU_ARM_DEBUG_T2"' -D_ING_APPLI_FULL_BINARY_NAME='"EMV_CUSTOM.AGN"' -D_SECDEL_ -D_USE_DEL_LIB_ $(INCLUDES_PATH)
# Specific assembler options
AS_SPEC_OPTS    := -mthumb  --defsym _ING_GNU_ARM_DEBUG_T2=1
AS_SPEC_OPTS    +=  $(INCLUDES_PATH)
# Specific linker options
LD_SPEC_OPTS    := 

#-------------------------------------------------------------------------------
# Compiler, linker, assembler options
# default + specific options
#-------------------------------------------------------------------------------
# Compiler options
CC_OPTS         := $(CC_DEF_OPTS) $(CC_SPEC_OPTS)
# Assembler options
AS_OPTS         := $(AS_DEF_OPTS) $(AS_SPEC_OPTS)
# Linker options
LD_OPTS         := $(LD_DEF_OPTS) $(LD_SPEC_OPTS)
#ObjDump options
OD_OPTS         := $(OD_DEF_OPTS)

#-------------------------------------------------------------------------------
# SRC_OBJS is the list of the project object files
#-------------------------------------------------------------------------------
SRC_OBJS        := \
$(OBJ_PATH)/convert.o \
$(OBJ_PATH)/cu_base.o \
$(OBJ_PATH)/cu_batch.o \
$(OBJ_PATH)/cu_black.o \
$(OBJ_PATH)/cu_comm.o \
$(OBJ_PATH)/cu_disk.o \
$(OBJ_PATH)/cu_entry.o \
$(OBJ_PATH)/cu_file.o \
$(OBJ_PATH)/cu_lang.o \
$(OBJ_PATH)/cu_logos.o \
$(OBJ_PATH)/cu_mess.o \
$(OBJ_PATH)/cu_more.o \
$(OBJ_PATH)/cu_param.o \
$(OBJ_PATH)/cu_pin.o \
$(OBJ_PATH)/cu_pinen.o \
$(OBJ_PATH)/cu_receipt.o \
$(OBJ_PATH)/cu_serv.o \
$(OBJ_PATH)/cu_str.o \
$(OBJ_PATH)/cu_term.o \
$(OBJ_PATH)/cu_trfile.o \
$(OBJ_PATH)/cu_UserInterface.o \
$(OBJ_PATH)/cu_UserInterfaceDisplay.o \
$(OBJ_PATH)/EPSTOOL_Convert.o \
$(OBJ_PATH)/EPSTOOL_PinEntry.o \
$(OBJ_PATH)/EPSTOOL_TlvTree.o \
$(OBJ_PATH)/EPSTOOL_Unicode.o \
$(OBJ_PATH)/gestion_param.o \
$(OBJ_PATH)/Globals.o \
$(OBJ_PATH)/Gpinpad.o \
$(OBJ_PATH)/MyTlvTree.o \
$(OBJ_PATH)/servcomm.o \
$(OBJ_PATH)/TlvTreeDel.o \
$(OBJ_PATH)/TrackIac.o \

#-------------------------------------------------------------------------------
# Dependencies
#-------------------------------------------------------------------------------
DEPENDENCIES    := \
$(BUILD_FILES_PATH)/makefile.mk

#===============================================================================
# Rule to make the project
#===============================================================================
#-------------------------------------------------------------------------------
# Rule for the binary files generation
#-------------------------------------------------------------------------------
$(BINARY_FILE): $(INTER_ELF_FILE)
	$(OBJ_COPY) -O binary $(INTER_AXF_FILE) $@
	@echo "'$@' binary file generated."

#===============================================================================
# Rule for startup files rules generation
#===============================================================================
START_OBJS := C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/startfiles/cstartupTplus.o \
C:/SDK11.16.0.PatchG/SDKTPLUS/HW_T2/gnu_434/startfiles/libcpatch.o \

END_OBJS   := 

#===============================================================================
# Rule for the link process
#===============================================================================
#-------------------------------------------------------------------------------
# Rule for the axf file generation
#-------------------------------------------------------------------------------
$(INTER_AXF_FILE): $(MAP_DEF_LOCATION) $(SRC_OBJS) $(LIBS)
	@echo "'$@' link in progress..."
	$(LD) $(LD_OPTS) \
	-T $< \
	-o $@ \
	$(START_OBJS)\
	$(SRC_OBJS) \
	 --start-group \
	$(LIBS) $(SYSTEM_LIBS) \
	--end-group \
	$(END_OBJS)\


#-------------------------------------------------------------------------------
# Rule for the elf file generation
#-------------------------------------------------------------------------------
$(INTER_ELF_FILE): $(INTER_AXF_FILE)
	$(SIZE) -A $< > $@

#===============================================================================
# Rule for the .lst Generation
#===============================================================================
$(LST_FILE): $(INTER_AXF_FILE)
	$(OBJ_DUMP) $(OD_OPTS) $<  > $@
	@echo "'$@' lst file generated."

#===============================================================================
# Rule for the compilation process
#===============================================================================
ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/convert.d
endif
$(OBJ_PATH)/convert.o: Src/convert.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/convert.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/convert.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_base.d
endif
$(OBJ_PATH)/cu_base.o: Src/cu_base.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_base.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_base.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_batch.d
endif
$(OBJ_PATH)/cu_batch.o: Src/cu_batch.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_batch.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_batch.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_black.d
endif
$(OBJ_PATH)/cu_black.o: Src/cu_black.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_black.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_black.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_comm.d
endif
$(OBJ_PATH)/cu_comm.o: Src/cu_comm.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_comm.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_comm.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_disk.d
endif
$(OBJ_PATH)/cu_disk.o: Src/cu_disk.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_disk.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_disk.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_entry.d
endif
$(OBJ_PATH)/cu_entry.o: Src/cu_entry.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_entry.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_entry.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_file.d
endif
$(OBJ_PATH)/cu_file.o: Src/cu_file.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_file.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_file.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_lang.d
endif
$(OBJ_PATH)/cu_lang.o: Src/cu_lang.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_lang.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_lang.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_logos.d
endif
$(OBJ_PATH)/cu_logos.o: Src/cu_logos.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_logos.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_logos.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_mess.d
endif
$(OBJ_PATH)/cu_mess.o: Src/cu_mess.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_mess.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_mess.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_more.d
endif
$(OBJ_PATH)/cu_more.o: Src/cu_more.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_more.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_more.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_param.d
endif
$(OBJ_PATH)/cu_param.o: Src/cu_param.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_param.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_param.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_pin.d
endif
$(OBJ_PATH)/cu_pin.o: Src/cu_pin.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_pin.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_pin.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_pinen.d
endif
$(OBJ_PATH)/cu_pinen.o: Src/cu_pinen.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_pinen.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_pinen.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_receipt.d
endif
$(OBJ_PATH)/cu_receipt.o: Src/cu_receipt.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_receipt.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_receipt.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_serv.d
endif
$(OBJ_PATH)/cu_serv.o: Src/cu_serv.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_serv.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_serv.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_str.d
endif
$(OBJ_PATH)/cu_str.o: Src/cu_str.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_str.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_str.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_term.d
endif
$(OBJ_PATH)/cu_term.o: Src/cu_term.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_term.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_term.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_trfile.d
endif
$(OBJ_PATH)/cu_trfile.o: Src/cu_trfile.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_trfile.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_trfile.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_UserInterface.d
endif
$(OBJ_PATH)/cu_UserInterface.o: Src/cu_UserInterface.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_UserInterface.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_UserInterface.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cu_UserInterfaceDisplay.d
endif
$(OBJ_PATH)/cu_UserInterfaceDisplay.o: Src/cu_UserInterfaceDisplay.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/cu_UserInterfaceDisplay.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cu_UserInterfaceDisplay.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/EPSTOOL_Convert.d
endif
$(OBJ_PATH)/EPSTOOL_Convert.o: Src/EPSTOOL_Convert.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/EPSTOOL_Convert.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/EPSTOOL_Convert.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/EPSTOOL_PinEntry.d
endif
$(OBJ_PATH)/EPSTOOL_PinEntry.o: Src/EPSTOOL_PinEntry.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/EPSTOOL_PinEntry.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/EPSTOOL_PinEntry.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/EPSTOOL_TlvTree.d
endif
$(OBJ_PATH)/EPSTOOL_TlvTree.o: Src/EPSTOOL_TlvTree.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/EPSTOOL_TlvTree.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/EPSTOOL_TlvTree.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/EPSTOOL_Unicode.d
endif
$(OBJ_PATH)/EPSTOOL_Unicode.o: Src/EPSTOOL_Unicode.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/EPSTOOL_Unicode.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/EPSTOOL_Unicode.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/gestion_param.d
endif
$(OBJ_PATH)/gestion_param.o: Src/gestion_param.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/gestion_param.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/gestion_param.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Globals.d
endif
$(OBJ_PATH)/Globals.o: Src/Globals.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/Globals.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Globals.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Gpinpad.d
endif
$(OBJ_PATH)/Gpinpad.o: Src/Gpinpad.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/Gpinpad.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Gpinpad.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/MyTlvTree.d
endif
$(OBJ_PATH)/MyTlvTree.o: Src/MyTlvTree.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/MyTlvTree.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/MyTlvTree.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/servcomm.d
endif
$(OBJ_PATH)/servcomm.o: Src/servcomm.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/servcomm.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/servcomm.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/TlvTreeDel.d
endif
$(OBJ_PATH)/TlvTreeDel.o: Src/TlvTreeDel.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/TlvTreeDel.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/TlvTreeDel.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/TrackIac.d
endif
$(OBJ_PATH)/TrackIac.o: Src/TrackIac.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@echo "'Src/TrackIac.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/TrackIac.o)
	@echo "done!"
endif


#===============================================================================
# Rule for project name and configuration name display
#===============================================================================
.PHONY: displayInfo
displayInfo:
	@echo "                                     *-*-*"
	@echo "--- Project '$(PROJECT_NAME)', Configuration '$(CFG_NAME)', Compiler '$(COMPILER_VERSION)' ---"

#===============================================================================
# Rule for build target progress info display
#===============================================================================
.PHONY: displayBuildInProgress
displayBuildInProgress:
	@echo "Build in progress..."

#===============================================================================
# Rule for output directories creation
#===============================================================================
createObjDir: | $(OBJ_PATH)

$(OBJ_PATH):
	@$(MKDIR) "$(OBJ_PATH)"

createBinDir: | $(BIN_PATH)

$(BIN_PATH):
	@$(MKDIR) "$(BIN_PATH)"


#===============================================================================
# Make build rule
#===============================================================================
.PHONY: build
build: displayInfo displayBuildInProgress createObjDir createBinDir $(BINARY_FILE)
	@echo "done!"
